services:
  - type: web
    name: hamro-learning
    runtime: docker
    plan: starter
    healthCheckPath: /
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: "Hamro Learning"
      - key: APP_KEY
        sync: false
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        sync: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: hamro-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: hamro-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: hamro-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: hamro-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: hamro-db
          property: password
      - key: MAIL_DRIVER
        value: log

databases:
  - name: hamro-db
    plan: free
    databaseName: hamro
    user: hamro
