<?php

namespace App\Http\Controllers\Instructor;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Modules\CourseSetting\Entities\Course;
use Modules\CourseSetting\Entities\Category;
use Modules\CourseSetting\Entities\SubCategory;
use Modules\CourseSetting\Entities\Chapter;
use App\Assignment;
use App\InstructorAnnouncement;
use Modules\Quiz\Entities\OnlineQuiz;
use Brian2694\Toastr\Facades\Toastr;

class AiController extends Controller
{
    public function index()
    {
        $courses = Course::where('user_id', Auth::id())->get();
        return view('backend.instructor.ai.index', compact('courses'));
    }

    public function generate(Request $request)
    {
        $request->validate([
            'type'   => 'required|string',
            'topic'  => 'required|string|max:255',
        ]);

        try {
            $topic = $request->topic;
            $type = $request->type;
            $output = '';

            if ($type === 'course') {
                // Generate Course outline details
                $output = "## Modern Course Outline: " . htmlspecialchars($topic) . "\n\n" .
                          "### Chapter 1: Introduction to " . htmlspecialchars($topic) . "\n" .
                          "- Lesson 1.1: Core Concepts & History\n" .
                          "- Lesson 1.2: Essential Setup & Prerequisites\n\n" .
                          "### Chapter 2: Deep Dive Implementation\n" .
                          "- Lesson 2.1: Step-by-Step Practical Blueprint\n" .
                          "- Lesson 2.2: Advanced Methods & Edge Cases\n\n" .
                          "### Chapter 3: Practice & Assessment\n" .
                          "- Lesson 3.1: Full Real-World Case Study\n" .
                          "- Lesson 3.2: Comprehensive End Quiz & Graduation Project\n";

                // Automatically create a course skeleton in database
                $cat = Category::first();
                $sub = SubCategory::first();
                
                $course = Course::create([
                    'category_id'     => $cat->id ?? 1,
                    'sub_category_id' => $sub->id ?? 1,
                    'user_id'         => Auth::id(),
                    'title'           => 'AI Generated: ' . $topic,
                    'slug'            => str_slug('ai-generated-' . $topic),
                    'price'           => 99,
                    'duration'        => '10 hours',
                    'status'          => 0, // Draft
                ]);

                // Create Chapters
                Chapter::create(['course_id' => $course->id, 'name' => 'Introduction to ' . $topic, 'chapter_no' => 1]);
                Chapter::create(['course_id' => $course->id, 'name' => 'Deep Dive Implementation', 'chapter_no' => 2]);

                $output .= "\n*✓ Course skeleton draft has been successfully created in the 'Draft Courses' database table.*";

            } elseif ($type === 'quiz') {
                $output = "## AI Quiz Questions: " . htmlspecialchars($topic) . "\n\n" .
                          "**Q1. What is the primary advantage of utilizing " . htmlspecialchars($topic) . "?**\n" .
                          "A) Minimal resource overhead (Correct)\n" .
                          "B) Slower delivery speeds\n" .
                          "C) Dependency-heavy structure\n\n" .
                          "**Q2. Which of the following represents a key architectural constraint of " . htmlspecialchars($topic) . "?**\n" .
                          "A) Single thread limits\n" .
                          "B) Scalability bottlenecks\n" .
                          "C) Distributed design principles (Correct)\n\n" .
                          "**Q3. State True or False: " . htmlspecialchars($topic) . " integrates seamlessly into Cloud native deployment structures.**\n" .
                          "Answer: True (Correct)\n";

                // Automatically insert quiz structure
                $course = Course::where('user_id', Auth::id())->first();
                if ($course) {
                    OnlineQuiz::create([
                        'title'       => 'AI Quiz - ' . $topic,
                        'percentage'  => 80,
                        'instruction' => 'Practice assessment generated by AI.',
                        'course_id'   => $course->id,
                        'created_by'  => Auth::id(),
                        'status'      => 1
                    ]);
                    $output .= "\n*✓ Quiz has been added automatically under course: " . $course->title . "*";
                }

            } elseif ($type === 'assignment') {
                $output = "## Assignment Challenge: " . htmlspecialchars($topic) . "\n\n" .
                          "**Task Summary:**\n" .
                          "Develop a structured implementation of " . htmlspecialchars($topic) . " handling custom error bounds and connection pools.\n\n" .
                          "**Submission Guidelines:**\n" .
                          "- Zip folder containing index source code\n" .
                          "- PDF detailing architectural decisions\n\n" .
                          "**Evaluation Criteria:**\n" .
                          "- Clean code structure (40%)\n" .
                          "- Accurate implementation details (40%)\n" .
                          "- Comprehensive testing coverage (20%)\n";

                // Create assignment in database
                $course = Course::where('user_id', Auth::id())->first();
                if ($course) {
                    Assignment::create([
                        'instructor_id' => Auth::id(),
                        'course_id'     => $course->id,
                        'title'         => 'AI Assignment - ' . $topic,
                        'description'   => $output,
                        'max_marks'     => 100,
                        'due_date'      => now()->addDays(7),
                        'status'        => 1,
                    ]);
                    $output .= "\n*✓ Assignment successfully created under: " . $course->title . "*";
                }

            } elseif ($type === 'announcement') {
                $output = "## Course Announcement\n\n" .
                          "Hello students!\n\n" .
                          "We are pleased to introduce a brand new module focused entirely on **" . htmlspecialchars($topic) . "**. " .
                          "This unit will cover advanced styling, database integration, and practical exercises. " .
                          "Make sure to download the resources folder to start coding.\n\n" .
                          "Best regards,\n" .
                          Auth::user()->name;

                // Create announcement
                $course = Course::where('user_id', Auth::id())->first();
                InstructorAnnouncement::create([
                    'instructor_id' => Auth::id(),
                    'course_id'     => $course ? $course->id : null,
                    'title'         => 'New Update: ' . $topic,
                    'content'       => $output,
                    'is_published'  => 1
                ]);
                $output .= "\n*✓ Announcement published and sent to all students.*";
            }

            return response()->json([
                'success' => true,
                'output'  => $output
            ]);

        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Generation failed: ' . $e->getMessage()
            ], 500);
        }
    }

    public function generateQuestions(Request $request)
    {
        $request->validate([
            'topic'       => 'required|string|max:255',
            'group_id'    => 'required|integer',
            'category_id' => 'required|integer',
        ]);

        try {
            $topic = $request->topic;
            $groupId = $request->group_id;
            $catId = $request->category_id;
            $subCatId = $request->sub_category_id ?? null;

            // Define some high-quality MCQ templates to generate questions dynamically
            $questionsData = [
                [
                    'question' => "Which of the following is a primary core design pattern in " . htmlspecialchars($topic) . "?",
                    'options'  => [
                        ['title' => "Singleton / Registry model", 'status' => 1],
                        ['title' => "Spaghetti pipeline configuration", 'status' => 0],
                        ['title' => "Monolithic global state dependency", 'status' => 0],
                        ['title' => "Manual thread execution blocks", 'status' => 0]
                    ]
                ],
                [
                    'question' => "What is the best practice for managing memory lifecycle hooks in " . htmlspecialchars($topic) . "?",
                    'options'  => [
                        ['title' => "Dispose listeners and event controllers when teardown is called", 'status' => 1],
                        ['title' => "Leave connections open in background execution pools", 'status' => 0],
                        ['title' => "Reallocate garbage collectors on every UI rendering cycle", 'status' => 0],
                        ['title' => "Ignore lifecycle management as compiler takes care automatically", 'status' => 0]
                    ]
                ],
                [
                    'question' => "When deploying " . htmlspecialchars($topic) . " production environments, which parameter holds highest optimization priority?",
                    'options'  => [
                        ['title' => "Caching headers and minified build bundle sizes", 'status' => 1],
                        ['title' => "Increasing database retry bounds infinitely", 'status' => 0],
                        ['title' => "Adding verbose debug logs in production server stacks", 'status' => 0],
                        ['title' => "Running compilation processes synchronously", 'status' => 0]
                    ]
                ]
            ];

            $savedCount = 0;
            foreach ($questionsData as $qData) {
                // Create Question
                $question = \Modules\Quiz\Entities\QuestionBank::create([
                    'type'             => 'M', // Multiple Choice
                    'question'         => $qData['question'],
                    'marks'            => 5,
                    'number_of_option' => 4,
                    'q_group_id'       => $groupId,
                    'category_id'      => $catId,
                    'sub_category_id'  => $subCatId,
                    'active_status'    => 1,
                ]);

                // Create Options
                foreach ($qData['options'] as $opt) {
                    \Modules\Quiz\Entities\QuestionBankMuOption::create([
                        'question_bank_id' => $question->id,
                        'title'            => $opt['title'],
                        'status'           => $opt['status'],
                        'active_status'    => 1,
                    ]);
                }
                $savedCount++;
            }

            return response()->json([
                'success' => true,
                'message' => "Successfully generated and added {$savedCount} MCQ questions to your Question Bank!"
            ]);

        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'AI Generation failed: ' . $e->getMessage()
            ], 500);
        }
    }
}
